README.md

46 involve other members as developers

---

mxv/settings.py
requirements.txt
review/admin.py
review/forms.py
review/models.py
review/templates/review/includes/form.html
review/templates/review/new_proposal.html
review/templates/review/proposal.html
review/templates/review/theme.html
review/urls.py
review/views.py

14 proposal browsing

---

mxv/settings.py
mxv/static/css/mxv.css
mxv/templates/mxv/base.html
mxv/templates/mxv/index.html
review/forms.py
review/templates/review/amendment.html
review/templates/review/delete_proposal.html
review/templates/review/edit_proposal.html
review/templates/review/index.html
review/templates/review/proposal.html
review/templates/review/theme.html
review/templates/review/track.html
review/urls.py
review/views.py

52 amendment browsing

---

mxv/templates/mxv/index.html
review/templates/review/index.html
review/templates/review/track.html

68 nominations broken

---

review/fixtures/review.json

74 missing proposal

---

review/admin.py
review/models.py
review/views.py

86 moderation requests

---

review/templates/review/support/rules.html

95 broken links

---

review/templates/review/support/rules.html

90 timeline

---

mxv/settings.py
mxv/urls.py
mxv/views.py

106 logging

---

mxv/templates/mxv/base.html
mxv/templates/mxv/tracking_tags.html

33 g aand fb

---

review/admin.py

111 amendments admin

---

mxv/static/css/mxv.css
review/admin.py
review/models.py
review/templates/admin/review/change_list.html
review/templates/review/comments/comment.html
review/templates/review/comments/moderate_comment.html
review/templates/review/proposals/proposal.html
review/templates/review/themes/theme.html

Closes #121, closes #125 and closes #126.

125 admin site browsing

---

mxv/static/css/mxv.css
mxv/templates/mxv/base.html
review/templates/review/proposals/proposal.html

129 share on facebook

---

mxv/static/css/mxv.css
mxv/templates/mxv/base.html
review/templates/review/proposals/proposal.html

Reverts PeoplesMomentum/mxv#131

Revert "129 share on facebook"

---

mxv/settings.py
review/emails/20180212_active_members.html
review/emails/20180212_inactive_members.html
review/emails/notes.txt

139 reminder emails

---

endbranch.sh
review/admin.py
review/templates/review/proposals/proposal.html

153 creation dates

---

review/templatetags/review_filters.py

164 hide scores

---

review/admin.py

166 voting results

---

review/fixtures/review.json
review/templates/review/track_votings/track2_voting.html

170 final final voting edits

---

review/emails/20180301_active_members_vote.html
review/emails/20180301_inactive_members_vote.html
review/emails/notes.txt

174 voting emails

---

review/templates/review/track_votings/vote_submitted.html

179 voting complete

---

review/templates/review/track_votings/track2_voting.html

185 spacing

---

mxv/templates/mxv/base.html
mxv/templates/mxv/footer.html

189 privacy statement

---

review/emails/20180329_active_members_elections.html
review/emails/20180329_inactive_members_elections.html

197 send elections email

---

mxv/templates/mxv/index.html
review/emails/notes.txt

199 remove ncg

---

mxv/templates/admin/submit_line.html
review/templates/admin/submit_line.html

204 missing admin buttons

---

mxv/admin.py
mxv/models.py
mxv/templates/admin/submit_line.html

207 email test address

---

review/fixtures/review.json
review/templates/review/track_votings/track3_voting.html

211 track3 voting edits

---

mxv/templates/mxv/footer.html

236 footer address

---

voting_intentions/fixtures/voting_intentions.json

253 petitions

---

requirements.txt

259 upgrade django

---

consultations/templates/consultations/thanks.html

262 update consultation

---

mxv/templates/mxv/footer.html

To reflect recent naming changes.

Replace Jeremy for Labour with Momentum Information

---

.gitignore
mxv/settings.py
mxv/templates/mxv/base.html
mxv/templates/mxv/navbar.html
mxv/templates/mxv/tracking_tags.html
package.json
questions/templates/questions/answers.html
questions/templates/questions/questions.html

May be easier to review each commit individually
- Fixed the yarn psql command (didn't work if you overrode db settings in .env)
- Proper .gitignore
- Show placeholder text on answer page if a question has no answers
- Proper handling for non-staff users
- If you have pending answers, say so on the questions list as well as the answers list
- Highlight answers link, rather than vote link
- Switch to Google Tag Manager instead of direct js loads

Assorted minor fixes

---

README.md
configs/example.env
dbpull.sh
package.json

#341 seemed to have a lot of other stuff in it; doing this clean one instead.

Clean dbpull for mxv

---

members/admin.py
members/models.py
members/tests.py
members/views.py
mxv/views.py

- There were multiple places where a nationbuilder_person record was not checked for first.
- Now validate the nationbuilder id; don't just assume it's present.

More fixes for profiles

---

mxv/templates/mxv/index.html
questions/templates/questions/questions.html
questions/tests.py
questions/views.py

- Questions page was broken entirely for candidates
- Removed "you can be the first" text for candidates
- Fixed the consultations card

Last minute Q&A fixes

---

members/admin.py

Otherwise we're stuck struggling with old records in SQL.

Allow editing of NB records from admin UI

---

questions/templates/questions/questions.html

on the loop, spaced cards better

card spacing

---

Pipfile
mxv/settings.py
mxv/templates/mxv/includes/form_field.html
package.json

- added django-countries
- added country select form on user's profiles

add country code select

---

Pipfile
mxv/settings.py
mxv/templates/mxv/includes/form_field.html
mxv/templates/mxv/meta_tags.html
package.json
questions/tests.py

add a country selector field on the profile update

Countryselect
